config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root 'pages#home'
  get 'about', to:'pages#about'
  resources :posts#, only: [:show,:index,:new,:create,:edit,:update,:destroy]
  resources :comments, only: [:new,:create]
  resources :users, only: [:index,:show]
  resources :friends
  resources :companions
  get 'search', to:'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/companion.rb
class Companion < ApplicationRecord
    belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
    #belongs_to :requestor, class_name: :User
    #belongs_to :receiver, class_name: :User
    #belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_one_attached :image
    validates :title, presence:true, length:{minimum:6, maximum:20}
    validates :description, presence:true, length:{maximum:150}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar 
  
  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: "150x150!").processed
    else
      "default_profile.jpg"
    end
  end

  #has_many :friend_requests_as_requestor, foreign_key: :requestor_id, class_name: :FriendRequest
  #has_many :friend_requests_as_receiver, foreign_key: :receiver_id, class_name: :FriendRequest
  #has_many :friend_requests
  has_many :friends
  has_many :companions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters,
            if: :devise_controller?


    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def new
        @comment=Comment.new
    end

    def create
        #byebug
        @comment=Comment.new(comment_params)
        if @comment.save
            flash[:notice]="Comment Successfully Added"
            #redirect_to post_path(@comment.post_id)
            redirect_back fallback_location: @post
        else
            flash.now[:alert]="Fill correct details"
            render 'new'
        end
    end

    def comment_params
        params.require(:comment).permit(:data,:post_id,:user_id)
    end

end

app/controllers/companions_controller.rb
class CompanionsController < ApplicationController

    def new
        @companion=Companion.new
    end

    def create
        #byebug
        @companion=Companion.new(companion_params)
        Companion.create(user_id:@companion.user_id,buddy:@companion.buddy)
        Companion.create(user_id:@companion.buddy,buddy:@companion.user_id)
        # if @companion.save
             flash[:notice]="New Friend Added"
             #byebug
              @friend=Friend.find_by(id:@companion.dummy)
              @friend.destroy
              redirect_to companions_path
        # else
        #     flash.now[:alert]="Fill correct details"
        #     render 'new'
        # end
    end

    def companion_params
        params.require(:companion).permit(:user_id,:buddy,:dummy)
    end

    def index
        @companions=current_user.companions
    end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def new
        @friend=Friend.new
    end

    def create
        #byebug
        @friend=Friend.new(friend_params)
        if @friend.save
            flash[:notice]="Friend Request Sent Successfully"
            redirect_to user_path(@friend.user_id)
            #redirect_back fallback_location: @post
        else
            flash.now[:alert]="Fill correct details"
            render 'new'
        end
    end

    def show
        @friend=Friend.find(params[:id])
    end

    def index
        @friends=current_user.friends
    end

    def destroy
        @friend=Friend.find(params[:id])
        @friend.destroy
        redirect_to friends_path
    end

    def friend_params
        params.require(:friend).permit(:user_id,:receiver_id,:status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :set_post, only: [:show,:edit,:update,:destroy]
    before_action :authenticate_user!, except: [:index,:show]
    def show
        #byebug
        #@post=Post.find(params[:id])
        @comments= @post.comments.order('comments.created_at DESC')
    end

    def index
        @posts=Post.all
        @posts= @posts.order('posts.created_at DESC')
    end

    def new
        @post=Post.new
    end

    def create
        #byebug
        @post=Post.new(post_params)
        if @post.save
            flash[:notice]="Post Successfully Created"
            redirect_to post_path(@post)
        else
            flash.now[:alert]="Fill correct details"
            render 'new'
        end
    end

    def edit
        #@post=Post.find(params[:id])
    end

    def update
        #@post=Post.find(params[:id])
        if @post.update(post_params)
            flash[:notice]="Post was updated successfully"
            redirect_to post_path(@post)
        else
            flash.now[:alert]="Fill correct details"
            render 'edit'
        end
    end

    def destroy
        #@post=Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private

    def set_post
        @post=Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title,:description,:image,:private,:user_id)
    end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user=User.find(params[:id])
    end

    def index
        @users=User.all
        @users= @users.order('users.created_at DESC')

    end

    def search
        @query=params[:query]
        @users=User.where("email LIKE ?",["%#{@query}%"])
        @users= @users.order('users.created_at DESC')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper       
end

app/views/comments/_demo.html.erb
<div class="page-content">
<h1 class="text-center mt-4"> Add Comment </h1>

    <div class="container">

    <div class="row justify-content-center">
    <div class="col-10">
    <%= form_with(model: @comment, local: true) do |f|%>
    
    
        <div class="form-group row justify-content-center">
            <div class="col-10">
                <%= f.text_area :data,rows:3, class:"form-control shadow-sm bg-white rounded",placeholder:"Comment on Post" %>
            </div>
            <div class="form-group row">
                <div class="col-10">
                    <%= f.number_field :post_id, id: :comment_post_id, class:"form-control", value: params[:param1], type: :hidden %>
                </div>   
            </div>
            <div class="form-group row">
                <div class="col-10">
                    <%= f.number_field :user_id, id: :comment_user_id, class:"form-control", value: current_user.id, type: :hidden %>
                </div>   
            </div>
        </div>

    
        <div class="form-group row justify-content-center">
            <%= f.submit "Add Comment", class:"btn btn-primary btn-lg" %>
        </div>
    
    <% end %>
    </div>
    <%=link_to '[ Return to Post listing page ]',posts_path %>
    </div>
    </div>
</div>

app/views/comments/new.html.erb
<div class="page-content">
<h1 class="text-center mt-4"> Add Comment </h1>

    <div class="container">

    <div class="row justify-content-center">
    <div class="col-10">
    <%= form_with(model: @comment, local: true) do |f|%>
    
    
        <div class="form-group row justify-content-center">
            <div class="col-10">
                <%= f.text_area :data,rows:3, class:"form-control shadow-sm bg-white rounded",placeholder:"Comment on Post" %>
            </div>
            <div class="form-group row">
                <div class="col-10">
                    <%= f.number_field :post_id, id: :comment_post_id, class:"form-control", value: params[:param1], type: :hidden %>
                </div>   
            </div>
            <div class="form-group row">
                <div class="col-10">
                    <%= f.number_field :user_id, id: :comment_user_id, class:"form-control", value: current_user.id, type: :hidden %>
                </div>   
            </div>
        </div>

    
        <div class="form-group row justify-content-center">
            <%= f.submit "Add Comment", class:"btn btn-primary btn-lg" %>
        </div>
    
    <% end %>
    </div>
    <%=link_to '[ Return to Post listing page ]',posts_path %>
    </div>
    </div>
</div>

app/views/companions/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Friends</h1>
<div class="container">
<% @companions.each do |companion| %>
    <% @friend=User.find_by(id:companion.buddy) %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <%= @friend.email.split("@")[0].capitalize %><br/>
                    <% if @friend.avatar.attached? %>
                        <%= image_tag(@friend.avatar_thumbnail) %>
                    <% else %>    
                        <%= image_tag("defualt.png", style:'width:30%') %>
                    <% end %>   
                </div>

                <div class="card-body">
                    <h5 class="card-title"><%= pluralize(@friend.posts.count,"Post") %></h5>
                    <%= link_to "View Profile", user_path(@friend), class: "btn btn btn-outline-success" %>
                </div>
        <div class="card-footer text-muted">
            <small>
            Joined <%= time_ago_in_words(@friend.created_at) %> ago
            </small>
        </div>
            </div>
        </div>
    </div>
<% end %>
</div>
</div>

app/views/friends/index.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Friend Requests</h1>
    <div class="container">
            <% @friends.each do |request| %>
                <div class="row justify-content-md-center" >
                    <% @user=User.find_by(id:request.receiver_id) %>
                    <div class="card" style="width: 18rem;">
                        <% if @user.avatar.attached? %>
                            <%= image_tag(User.find_by(id:request.receiver_id).avatar_thumbnail) %>
                        <% else %>    
                            <%= image_tag("defualt.png", style:'width:30%') %>
                        <% end %> 
                        <div class="card-body">
                            <h5 class="card-title">From: <%=@user.email %></h5>
                            <%= link_to "View", friend_path(request), class:"btn btn-outline-primary" %>
                        </div>
                    </div>

                    </div>
                <br/>
            <% end %>    
    </div>
</div>

app/views/friends/show.html.erb
<div id="page-content">
    <% @user=User.find_by(id:@friend.receiver_id) %>
    <h1 class="text-center mt-4"><%=@user.email%></h1>
    <div class="container">
                <div class="row justify-content-md-center" >
                    
                    <div class="card" style="width: 18rem;">
                        <% if @user.avatar.attached? %>
                            <%= image_tag(@user.avatar_thumbnail) %>
                        <% else %>    
                            <%= image_tag("defualt.png", style:'width:30%') %>
                        <% end %> 
                        <div class="card-body">
                            <h5 class="card-title">From: <%=@user.email %></h5>


                            <%= form_with scope: :companion, url: companions_path, local: true do |f|%>
    
    
                                <div class="form-group row justify-content-center">
                                    <div class="form-group row">
                                        <div class="col-10">
                                            <%= f.number_field :user_id, id: :companion_user_id, class:"form-control", value: @friend.user_id, type: :hidden %>
                                        </div>   
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-10">
                                            <%= f.number_field :buddy, class:"form-control", value: @friend.receiver_id, type: :hidden %>
                                        </div>   
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-10">
                                            <%= f.number_field :dummy, class:"form-control", value: @friend.id, type: :hidden %>
                                        </div>   
                                    </div>
                                </div>
                              
                              
                                    <%= f.submit "Accept", class:"btn btn-outline-success" %>
                              
                            <% end %>



                            <br/>
                            <%= link_to "Decline", friend_path(@friend), class:"btn btn-outline-danger", method: :delete, data: {confirm:"Are you sure?"}  %>
                        </div>
                    </div>

                    </div>
                <br/>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container" >
<% flash.each do |name,msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>    
  <% end %>  
</div>  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Social Networking', root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> 
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'About',about_path,class:"nav-link" %>
      </li>
      
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In',new_user_session_path,class:"nav-link" %>
        </li>
      <% end %> 
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Post
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'All Posts', posts_path,class:"dropdown-item" %>
          <% if user_signed_in? %>
            <%= link_to 'Create new Post', new_post_path,class:"dropdown-item" %>
          <% end %>  
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
           <%= link_to 'Users', users_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
            <input class="form-control mr-sm-2" type="search" placeholder="search any user" aria-label="Search" name="query">
            <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
          </form>
        </li>  

        <li class="nav-item">
            <%= link_to 'Friend Requests '+(current_user.friends.count).to_s,friends_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
    <div class="nav-item dropdown my-2 my-lg-0">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email.split("@")[0].upcase %>
        </a>
        <div class="dropdown-menu my-2 my-lg-0" aria-labelledby="navbarDropdown">
          <%= link_to 'Edit Profile',edit_user_registration_path,class:"dropdown-item" %>
          <%= link_to 'Friends '+(current_user.companions.count).to_s, companions_path, class:"dropdown-item" %> 
          <%= link_to 'Sign Out',destroy_user_session_path,method: :delete,class:"dropdown-item" %>
      </div>
    <% end %>  
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Social Networking App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About Page <h1><br/><br/>

<%=link_to 'Post listing page',posts_path %> | 
<%=link_to 'Home page',root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container" >
    <div class="jumbotron text-center text-white">
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <% if !user_signed_in? %>
        <%= link_to 'Sign up',new_user_registration_path, class:"btn btn-outline-primary btn-lg m-4" %>
        <%= link_to 'Sign in',new_user_session_path, class:"btn btn-outline-success btn-lg" %>
    <% end %>
    </div>
</div>

app/views/posts/_form.html.erb
<div class="container">

<div class="row justify-content-center">
<div class="col-10">
<%= render 'shared/errors' %>
<%= form_with(model: @post,class:"shadow-none p-3 mb-3 bg-dark rounded", local: true) do |f|%>

    <div class="form-group row">
        <%= f.label :title, class:"col-2 col-form-label text-white font-weight-bold" %>
        <div class="col-10">
             <%= f.text_field :title, class:"form-control shadow-sm bg-white rounded",placeholder:"Title for Post" %>
        </div>
    </div>

    <div class="form-group row">
        <%= f.label :description, class:"col-2 col-form-label text-white font-weight-bold" %>
        <div class="col-10">
            <%= f.text_area :description,rows:10, class:"form-control shadow-sm bg-white rounded",placeholder:"Description of Post" %>
        </div>   
    </div>

    <div class="field form-group row">
        <%= f.label :image, class:"col-2 col-form-label text-white font-weight-bold" %>
        <%= f.file_field :image, class:"col-form-label text-white font-weight-bold" %>
    </div>

    <div class="form-check">
        <%= f.check_box :private %>
        <%= f.label :private, class:"col-2 col-form-label text-white font-weight-bold"%>
    </div>

    <div class="form-group row">
        <div>
            <%= f.number_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden %>
        </div>   
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit class:"btn btn-primary btn-lg" %>
    </div>

<% end %>
</div>
<%=link_to '[ Return to Post listing page ]',posts_path %>
</div>
</div>

app/views/posts/edit.html.erb
<div class="page-content">
<h1 class="text-center mt-4"> Edit Post </h1>

<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<div class="page-content">
  <h1 class="text-center mt-4"> Listing all the Posts </h1>

  <div class="container">
    <% @posts.each do|post| %>
      <% if !post.private? || post.user==current_user %>
        <div class="row justify-content-md-center mt-4">
          <div class="">
            <div class="card" style="width: 28rem;">
              <%= link_to image_tag(post.image,style:'width:100%'),post_path(post) %>
              <div class="card-body">
                <h5 class="card-title text-center"><%= post.title %></h5>
                <p class="card-text text-center"><%= post.description %></p>

                <div class="font-italic mt-2 text-center">
                  <button type="button" class="btn btn-primary">
                    Comments <span class="badge badge-light"><%= post.comments.count %></span>
                  </button>
                  <%#<button type="button" class="btn btn-primary">
                    Likes <span class="badge badge-light">9</span>
                  </button>#%>
                </div>

                <div class="mt-4 text-center">
                  <%= link_to 'View',post_path(post),class:"btn btn-outline-success"%>

                  <% if post.user==current_user %>
                    <%= link_to 'Edit',edit_post_path(post),class:"btn btn-outline-primary" %>
                    <%= link_to 'Delete',post_path(post),class:"btn btn-outline-danger",method: :delete, data: {confirm:"Are you sure?"} %>
                  <% end %>  
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="page-content">
<h1 class="text-center mt-4"> Create new Post </h1>

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div class="container mt-4">
<div class="card">
  <div class="card-header text-center text-primary">
     by <%= @post.user.email.split("@")[0] %>
  </div>
  <div class="card-body">
    <h5 class="card-title text-center"><u><%= @post.title %></u></h5>
    <p class="card-text"><%= simple_format(@post.description) %></p>
    <% if user_signed_in? && @post.user!=current_user %>
      <% link_to 'Comment', new_comment_path(:param1 => @post.id),class:"btn btn-outline-primary" %>
      <% link_to 'Like',new_comment_path,class:"btn btn-outline-primary" %>
    <% end %>
  </div>
  <div class="card-footer text-muted text-center">
    Created on: <%=@post.created_at.to_date.strftime('%d-%m-%Y')%>
  </div>
</div>

<br/>
<% if user_signed_in? && @post.user!=current_user %>
<%= form_with scope: :comment, url: comments_path, local: true do |f|%>
    
    
  <div class="form-group row justify-content-center">
      <div class="col-10">
          <%= f.text_area :data,rows:3, class:"form-control shadow-sm bg-white rounded",placeholder:"Comment on Post" %>
      </div>
      <div class="form-group row">
          <div class="col-10">
              <%= f.number_field :post_id, id: :comment_post_id, class:"form-control", value: @post.id, type: :hidden %>
          </div>   
      </div>
      <div class="form-group row">
          <div class="col-10">
              <%= f.number_field :user_id, id: :comment_user_id, class:"form-control", value: current_user.id, type: :hidden %>
          </div>   
      </div>
  </div>


  <div class="form-group row justify-content-center">
      <%= f.submit "Add Comment", class:"btn btn-primary btn-lg" %>
  </div>

<% end %>
<% end %>

<br/>
<h3><b>Comments:-</b></h3>
<% if @comments.count==0 %>
    <p class="text-center">No Comments Yet</p>
<% else %> 
  <% @comments.each do |comment| %>
    <div class="card mt-4">
    <div class="card-header">
      by <%= comment.user.email.split("@")[0].capitalize %>
    </div>
    <div class="card-body">
      <%= comment.data %>
    </div>
  </div>
  <% end %>  
<% end %>  
</div>

app/views/shared/_errors.html.erb
<% if @post.errors.any? %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the post from being created</h4>
  <ul>
    <% @post.errors.full_messages.each do|msg| %>
        <li><%= msg %></li>
    <% end %>    
   </ul> 
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Users</h1>
<div class="container">
<% @users.each do |user| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <%= user.email.split("@")[0].capitalize %><br/>
                    <% if user.avatar.attached? %>
                        <%= image_tag(user.avatar_thumbnail) %>
                    <% else %>    
                        <%= image_tag("defualt.png", style:'width:30%') %>
                    <% end %>   
                </div>

                <div class="card-body">
                    <h5 class="card-title"><%= pluralize(user.posts.count,"Post") %></h5>
                    <%= link_to "View Profile", user_path(user), class: "btn btn btn-outline-success" %>
                </div>
        <div class="card-footer text-muted">
            <small>
            Joined <%= time_ago_in_words(user.created_at) %> ago
            </small>
        </div>
            </div>
        </div>
    </div>
<% end %>
</div>
</div>

app/views/users/search.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Search Results</h1>
<div class="container">
<% if @users.count==0 %>
    <br/><br/><br/><br/><h3 class="row justify-content-md-center"> No result found! <h3>
<% else %>
<% @users.each do |user| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <%= user.email.split("@")[0].capitalize %><br/>
                    <% if user.avatar.attached? %>
                        <%= image_tag(user.avatar_thumbnail) %>
                    <% else %>    
                        <%= image_tag("defualt.png", style:'width:30%') %>
                    <% end %>    
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= pluralize(user.posts.count,"Post") %></h5>
                    <%= link_to "View Profile", user_path(user), class: "btn btn btn-outline-success" %>
                </div>
        <div class="card-footer text-muted">
            <small>
            Joined <%= time_ago_in_words(user.created_at) %> ago
            </small>
        </div>
            </div>
        </div>
    </div>
<% end %>
<% end %>   
</div>
</div>